name: mobile_test_daniel_vofchuk
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.0.0
  flutter_svg: ^0.22.0
  shimmer: ^2.0.0
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - icons/

  fonts:
    - family: Segoe UI
      fonts:
        - asset: font/Segoe UI Bold Italic.ttf
          weight: 900
          style: italic
        - asset: font/Segoe UI.ttf
        - asset: font/Segoe UI Bold.ttf
          weight: 900
        - asset: font/Segoe UI Italic.ttf
          style: italic

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
